### ISSUE TITLE
SAC with gSDE not working on MinitaurBulletEnv-v0

### ISSUE THREAD

**Issue by markub3327** [DLR-RM/rl-baselines3-zoo#117]
Hello @araffin,

  I trained the agent on MinitaurBulletEnv-v0 but without success. I tried to use the Min-max normalization method because every observation has its own range of values, but it's not working and without normalization, I get better results. I test it on my platform [RL Toolkit](https://github.com/markub3327/rl-toolkit), which is based on TF but is almost the same as yours.

Why is MinitaurBulletEnv-v0 not working, when the agent [here](https://www.tensorflow.org/agents/tutorials/7_SAC_minitaur_tutorial) is learning?

My tested hyperparameters:
  | Hyperparameter | Value |
  | ---------------- | ------ |
  | n_timesteps | 1000000 |
  | learning_rate | 0.00073 |
  | batch_size | 256 |
  | buffer_size  | 1000000 |
  | ent_coef | auto |
  | gamma | 0.99 |
  | learning_starts | 10000 |
  | update_interval | 64 |

When you'll find better hyperparameters or anything else please share it with me.

<img width="898" alt="Snímka obrazovky 2021-06-21 o 9 09 42" src="https://user-images.githubusercontent.com/74611856/122723662-82a73400-d273-11eb-9427-20a23991abae.png">

https://user-images.githubusercontent.com/74611856/122724806-9606cf00-d274-11eb-8212-6c414012e29e.mp4

Thanks a lot.

**Comment by araffin** [comment]
Hello,
So after a quick trial, I found those hyperparameters to be working (for unstructured noise):
```yaml
MinitaurBulletEnv-v0:
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 3e-4
  buffer_size: 100000
  batch_size: 256
  ent_coef: 'auto'
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000
```

with gSDE (the noise sampling frequency is quite small and therefore quite close to unstructured noise):

```yaml
MinitaurBulletEnv-v0:
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 3e-4
  buffer_size: 1000000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.99
  train_freq: 4
  gradient_steps: 4
  learning_starts: 10000
  use_sde: True
  policy_kwargs: "dict(log_std_init=-3)"
```

As mentioned in the gSDE paper (the arxiv  version will be updated tomorrow: https://arxiv.org/abs/2005.05719 ), the main strength of gSDE is not in simulation but on a real robot (as it reduces wear-and-tear while keeping good performance).

I will try to upload the learning curves and trained agent soon.

**Comment by araffin** [comment]
The training reward with unstructured noise:

![Training_Episodic_Reward](https://user-images.githubusercontent.com/1973948/122769631-02012b80-d2a5-11eb-9a4b-d55d784efb35.png)

**Comment by markub3327** [comment]
I thought that the MinitaurBulletEnv-v0 is Sim-to-Real problematics and gSDE is useful for that too. I will test it with a higher update freq than 64 and a lower learning rate.

Thanks.

**Comment by araffin** [comment]
>I thought that the MinitaurBulletEnv-v0 is Sim-to-Real problematics and gSDE is useful for that too.

gSDE was designed to run RL directly on real robots (no sim2real) even though it should help for sim2real pb too (however, I'm not sure if MinitaurBulletEnv-v0 is Sim-to-Real problematics or not).

**Comment by markub3327** [comment]
I read about Minitaur [here](https://arxiv.org/pdf/1804.10332.pdf). Can you share with me please, Actor loss, Critic loss, Steps (at episode) charts for detailed analysis of my problematics. I try your hyperparameters without significant improvement.

I use client-server architecture for training RL agents (with Reverb).

Thanks.

**Comment by araffin** [comment]
Best for you would be to do a run using SB3 + the rl zoo:
the hyperparams:
```yaml
MinitaurBulletEnv-v0:
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 3e-4
  buffer_size: 1000000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.99
  train_freq: 4
  gradient_steps: 4
  learning_starts: 10000
  use_sde: True
  policy_kwargs: "dict(log_std_init=-3)"
```

Training with tensorboard (logging to `/tmp/tensorboard_sb3/` here)
```
python train.py --algo sac --env MinitaurBulletEnv-v0 -tb /tmp/tensorboard_sb3/ --num-threads 2 --eval-episodes 20 --n-eval-envs 5
```

The learning curves (blue is unstructured noise, orange with gSDE):
Note that the true performance of SAC is higher because I display the training reward here, not the evaluation one using the deterministic controller.
![Training_Episodic_Reward](https://user-images.githubusercontent.com/1973948/122932617-2d038200-d36e-11eb-8510-d18959d41ada.png)

>PS: I think that it is because the learner is faster than the agent. When I try for example AntBulletEnv-v0 everything is good, but the agent plays faster than the learner. In this case, the learner has more data to training from.

you mean that you are learning in parallel of data collection?
Yes this can be definitely a problem.
