### ISSUE TITLE
eval env is not wrapped with VecTranspose when using DDPG+HER

### ISSUE THREAD

**Issue by JimLiu1213** [DLR-RM/rl-baselines3-zoo#135]
I am using zoo to train custom env with DDPG +HER. Images (64, 64, 4) and positions (goal (3,1) )are my input. 

The warning occurred: 
```
Training and eval env are not of the same type<stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object
 at 0x7fa205a187d0> != <stable_baselines3.common.vec_env.vec_frame_stack.VecFrameStack object at 0x7fa205a18910>
```

I tracked my terminal: 
```
Stacking 4 frames
Stacking 4 frames
Applying normal noise with std 0.1
Using cuda device
Wrapping the env in a VecTransposeImage.
```
It seems that only training env was wrapped with VecTranspose. So, how can I deal with this issue. Thank you
When I disabled frame stack: 
```
Training and eval env are not of the same type<stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object 
at 0x7f5ca3b3ab90> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f5ca3b4e150>
```
This is my parameters:
```
FoodHuntingHSR-v0: 
  <<: *pybullet-defaults
  env_wrapper:
#    - gym.wrappers.resize_observation.ResizeObservation:
#        shape: 40
#    - gym.wrappers.gray_scale_observation.GrayScaleObservation:
#        keep_dim: true
  frame_stack: 4
  n_timesteps: !!float 1e6
  policy: 'CnnPolicy'
  batch_size: 128
  gamma: 0.98
  device: 'cuda'
  buffer_size: 200000
  learning_starts: 500
  noise_type: 'normal'
  noise_std: 0.1
  gradient_steps: 1
  train_freq: 1
  learning_rate: !!float 1e-3
  policy_kwargs: "dict(net_arch=[400,300], features_extractor_kwargs=dict(features_dim=256))"
```
**System Info**
Describe the characteristic of your environment:
 * pip install SB3
 
 * PyTorch 1.8.0
 

**Additional context**
