### ISSUE TITLE
where is mujoco-defaults 

### ISSUE THREAD

**Issue by mrzhuzhe** [DLR-RM/rl-baselines3-zoo#209]
**Describe the bug**
what is `mujoco-defaults` value ? where this Syntactic sugar come from ? 

`
Humanoid-v3:
  <<: *mujoco-defaults
  n_timesteps: !!float 2e6
`

**Code example**
rl-baselines3-zoo/hyperparams/sac.yml

**System Info**
not about

**Comment by qgallouedec** [comment]
From here:

https://github.com/DLR-RM/rl-baselines3-zoo/blob/a520d52739d18953e1290189be377c794a3da5bf/hyperparams/sac.yml#L193

This line allows to store `HalfCheetah-v3` parameters under the name `mujoco-defaults`. 

This line 

https://github.com/DLR-RM/rl-baselines3-zoo/blob/a520d52739d18953e1290189be377c794a3da5bf/hyperparams/sac.yml#L208

allows to use the parameters that are stored under the name of `mujoco-defaults`.

Though, you can read

```yml
Humanoid-v3:
  policy: 'MlpPolicy'
  learning_starts: 10000
  n_timesteps: !!float 2e6
```
